#define is_vampire_job(job_type)  (istype(job_type, /datum/job/vampire))
#define is_prince_job(job_type) (istype(job_type, /datum/job/vampire/prince))
#define is_sabbatist(job_type) (istype(job_type, /datum/job/vampire/sabbatpack || /datum/job/vampire/sabbatpriest || /datum/job/vampire/sabbatductus))
#define is_sabbat_priest(job_type) (istype(job_type, /datum/job/vampire/sabbatpriest))
#define is_sabbat_ductus(job_type) (istype(job_type, /datum/job/vampire/sabbatductus))
#define iskindred(mob) (get_kindred_splat(mob))
#define isghoul(mob) (get_ghoul_splat(mob))
#define isgarou(mob) (get_garou_splat(mob))
